title: Chenxi (Susie) Tao # your name (or website title) here
logo: "images/professional_photo_small.JPG.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  MS in Business Analytics Candidate (STEM)
  Consultant at Simon Vision Consulting
  Data-driven Decision Making
  Consulting | Pricing | Data Analyst
  <br><br>
  <a href="https://www.linkedin.com/in/chenxitao/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
