title: Chenxi Tao # your name (or website title) here
logo: "images/professional_photo_2.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Susie Tao. 
  <br><br>
  I'm now an MSBA student of Simon Business School, University of Rochester.
  <br><br>
  <a href="https://www.linkedin.com/in/chenxitao/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
